package com.example.billing_platform_mis.repository;

import com.example.billing_platform_mis.entity.Report;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

//Repository for Report entity supporting report generation audit and tracking
@Repository
public interface ReportRepository extends JpaRepository<Report, Long> {
    
    //Find reports generated by a specific user
    List<Report> findByGeneratedByIdOrderByCreatedAtDesc(Long userId);
    
    //Find reports by report type
    List<Report> findByReportTypeOrderByCreatedAtDesc(String reportType);
    
    //Find reports by user and report type
    List<Report> findByGeneratedByIdAndReportTypeOrderByCreatedAtDesc(Long userId, String reportType);
    
    //Find reports for a specific target entity
    List<Report> findByTargetEntityIdOrderByCreatedAtDesc(Long targetEntityId);
    
    //Find reports generated within a date range
    @Query("SELECT r FROM Report r WHERE r.createdAt BETWEEN :startDate AND :endDate " +
           "ORDER BY r.createdAt DESC")
    List<Report> findByCreatedAtBetween(@Param("startDate") LocalDateTime startDate,
                                      @Param("endDate") LocalDateTime endDate);
    
    //Find reports by user within a date range
    @Query("SELECT r FROM Report r WHERE r.generatedBy.id = :userId " +
           "AND r.createdAt BETWEEN :startDate AND :endDate " +
           "ORDER BY r.createdAt DESC")
    List<Report> findByUserAndDateRange(@Param("userId") Long userId,
                                      @Param("startDate") LocalDateTime startDate,
                                      @Param("endDate") LocalDateTime endDate);
    
    //Find reports covering a specific date range
    @Query("SELECT r FROM Report r WHERE r.dateFrom <= :endDate AND r.dateTo >= :startDate " +
           "ORDER BY r.createdAt DESC")
    List<Report> findReportsCoveringDateRange(@Param("startDate") LocalDate startDate,
                                            @Param("endDate") LocalDate endDate);
    
    //Count reports by type for analytics
    long countByReportType(String reportType);
    
    //Count reports generated by user
    long countByGeneratedById(Long userId);
    
    //Find most frequently generated report types
    @Query("SELECT r.reportType, COUNT(r) as reportCount FROM Report r " +
           "GROUP BY r.reportType " +
           "ORDER BY reportCount DESC")
    List<Object[]> findMostFrequentReportTypes();
    
    //Find most active report generators
    @Query("SELECT r.generatedBy, COUNT(r) as reportCount FROM Report r " +
           "GROUP BY r.generatedBy " +
           "ORDER BY reportCount DESC")
    List<Object[]> findMostActiveReportGenerators();
    
    //Find recent reports for dashboard (last 30 days)
    @Query("SELECT r FROM Report r WHERE r.createdAt >= :thirtyDaysAgo " +
           "ORDER BY r.createdAt DESC")
    List<Report> findRecentReports(@Param("thirtyDaysAgo") LocalDateTime thirtyDaysAgo);
    
    //Count reports generated today
    @Query("SELECT COUNT(r) FROM Report r WHERE CAST(r.createdAt AS date) = CURRENT_DATE")
    long countReportsGeneratedToday();
    
    //Count reports generated this week
    @Query("SELECT COUNT(r) FROM Report r WHERE r.createdAt >= :weekStart")
    long countReportsGeneratedThisWeek(@Param("weekStart") LocalDateTime weekStart);
    
    //Count reports generated this month
    @Query("SELECT COUNT(r) FROM Report r WHERE r.createdAt >= :monthStart")
    long countReportsGeneratedThisMonth(@Param("monthStart") LocalDateTime monthStart);
    
    //Find reports with user details for admin view
    @Query("SELECT r FROM Report r " +
           "JOIN FETCH r.generatedBy " +
           "ORDER BY r.createdAt DESC")
    List<Report> findAllWithUserDetails();
    
    //Find report generation trends by date
    @Query("SELECT CAST(r.createdAt AS date) as reportDate, COUNT(r) as reportCount FROM Report r " +
           "WHERE r.createdAt >= :startDate " +
           "GROUP BY CAST(r.createdAt AS date) " +
           "ORDER BY reportDate DESC")
    List<Object[]> findReportGenerationTrends(@Param("startDate") LocalDateTime startDate);
}